### PR TITLE
Create app.json

### PR DESCRIPTION
**Pull request by ghost**
I did this so I can just deploy it to Heroku

### CODE REVIEW

**Comment by falkirks** [comment]
Good idea, but it has your information, so I can't merge it.

**Comment by ghost** [comment]
lel its a good thing u dont merge it because its not working on heroku and i tested it

**Comment by falkirks** [comment]
:stuck_out_tongue: I'm running mine on Heroku. It needs a Mongo database.

**Comment by ghost** [comment]
how?

**Comment by falkirks** [comment]
@KairusDarkSeeker The instructions are in the `README.md`

**Comment by ghost** [comment]
idk how to use cmd.exe yet and my pc is in vista not in win 7

**Comment by ghost** [comment]
btw is there a way to run it on the lovely heroku android app?

**Comment by falkirks** [comment]
@KairusDarkSeeker I don't know, I haven't tried.

**Comment by ghost** [comment]
ok

**Pull request closed without merging**
